name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        run: |
          set -e

          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

          ssh -i ~/.ssh/id_rsa ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            set -e

            cd /home/${{ secrets.SERVER_USER }}/startlight-api

            echo "📊 Disk usage BEFORE cleanup"
            df -h /
            sudo docker system df

            echo "📦 Syncing repo..."
            git fetch origin main
            git reset --hard origin/main

            echo "🧹 Freeing Docker space..."
            sudo docker image prune -af
            sudo docker builder prune -af

            echo "📊 Disk usage AFTER cleanup"
            df -h /
            sudo docker system df

            echo "🚀 Rebuild & restart (no downtime)..."
            sudo docker compose up -d --build


            echo "📊 Disk usage AFTER deploy"
            df -h /
            sudo docker system df

            sleep 5
            echo "📜 Logs:"
            sudo docker compose logs --tail=50
          EOF

# name: Deployment

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Deploy via SSH
#         run: |
#           set -e

#           mkdir -p ~/.ssh
#           echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
#           chmod 600 ~/.ssh/id_rsa
#           ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

#           ssh -i ~/.ssh/id_rsa ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
#             set -e

#             cd /home/${{ secrets.SERVER_USER }}/startlight-api

#             echo "📦 Syncing repo..."
#             git fetch origin main
#             git reset --hard origin/main

#             echo "🧹 Freeing Docker space..."
#             sudo docker image prune -af
#             sudo docker builder prune -af

#             echo "🚀 Rebuild & restart (no downtime)..."
#             sudo docker compose up -d --build

#             sleep 5

#             echo "📜 Logs:"
#             sudo docker compose logs --tail=50
#           EOF
